// SubmitPage — submit a new free resource WITHOUT logging in.
// B/W monochrome theme. No backend, no auth.
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api.js';
import { config } from '../config.js';
import { useToast } from '../components/Toast.jsx';
import Layout from '../components/Layout.jsx';
import TierBadge from '../components/TierBadge.jsx';

const TIERS = [
  { value: 'free-tier', label: 'Free Tier', desc: 'A genuinely free plan (not just a trial).' },
  { value: 'free-trial', label: 'Free Trial', desc: 'Time-limited free access.' },
  { value: 'free-forever', label: 'Free Forever', desc: 'Free forever, no expiry.' },
  { value: 'open-source', label: 'Open Source', desc: 'Self-hostable open-source tool.' },
];

const EMPTY = {
  categoryName: '',
  newCategoryDescription: '',
  name: '',
  url: '',
  description: '',
  tier: 'free-tier',
  tags: '',
  submittedBy: '',
  note: '',
};

function validateLocal(form) {
  const errors = {};
  if (!form.categoryName.trim()) errors.categoryName = 'Pick or create a category.';
  if (form.name.trim().length < 2) errors.name = 'At least 2 characters.';
  else if (form.name.trim().length > 80) errors.name = 'At most 80 characters.';
  else if (form.name !== form.name.trim()) errors.name = 'No leading/trailing spaces.';

  try {
    const u = new URL(form.url.trim());
    if (!['http:', 'https:'].includes(u.protocol)) errors.url = 'Must be http(s).';
  } catch {
    errors.url = 'Enter a valid URL.';
  }

  if (form.description.trim().length < 10) errors.description = 'At least 10 characters.';
  else if (form.description.trim().length > 400) errors.description = 'At most 400 characters.';

  if (form.tags.trim()) {
    const tags = form.tags.split(',').map((t) => t.trim()).filter(Boolean);
    if (tags.length > 10) errors.tags = 'At most 10 tags.';
    else if (tags.some((t) => !/^[a-z0-9-]{2,20}$/i.test(t)))
      errors.tags = 'Tags: 2-20 chars, letters/numbers/hyphens only.';
  }
  if (form.submittedBy && form.submittedBy.length > 60) errors.submittedBy = 'At most 60 characters.';
  return errors;
}

function buildIssueBody(form) {
  const tags = form.tags.split(',').map((t) => t.trim().toLowerCase()).filter(Boolean);
  const payload = {
    categoryName: form.categoryName.trim(),
    newCategoryDescription: form.newCategoryDescription.trim() || null,
    submitterNote: form.note.trim() || null,
    entry: {
      name: form.name.trim(),
      url: form.url.trim(),
      description: form.description.trim(),
      tier: form.tier,
      tags,
      submittedBy: form.submittedBy.trim().replace(/^@/, '') || null,
    },
  };

  return [
    '### Resource submission',
    '',
    'This issue was generated by the [Free4Techies](https://free4techies.pages.dev) submit form.',
    'A GitHub Action will parse the JSON below, validate it, and open an auto-merging pull request that updates `public/resources.json`.',
    '',
    'Please **do not edit the JSON block below** unless you know the schema. You can add comments above it.',
    '',
    '```json',
    JSON.stringify(payload, null, 2),
    '```',
    '',
  ].join('\n');
}

export default function SubmitPage() {
  const { push } = useToast();
  const [form, setForm] = useState(EMPTY);
  const [categories, setCategories] = useState([]);
  const [submitting, setSubmitting] = useState(false);
  const [result, setResult] = useState(null);
  const [touched, setTouched] = useState({});

  useEffect(() => {
    api.categories().then((cats) => setCategories(cats)).catch(() => {});
  }, []);

  const errors = useMemo(() => validateLocal(form), [form]);
  const isValid = Object.keys(errors).length === 0;

  const set = (key, value) => setForm((f) => ({ ...f, [key]: value }));
  const onBlur = (key) => setTouched((t) => ({ ...t, [key]: true }));

  const submit = (e) => {
    e.preventDefault();
    setTouched({ categoryName: true, name: true, url: true, description: true, tags: true, submittedBy: true });
    if (!isValid) {
      push({ type: 'error', title: 'Check the form', message: 'Please fix the highlighted fields.' });
      return;
    }

    setSubmitting(true);
    const title = `[Resource] ${form.name.trim()}`;
    const body = buildIssueBody(form);
    const url =
      config.issueTemplateUrl +
      encodeURIComponent(title) +
      `&body=${encodeURIComponent(body)}`;

    setResult({ url, title });
    setForm(EMPTY);
    setTouched({});
    setSubmitting(false);
    push({
      type: 'success',
      title: 'Ready to submit!',
      message: 'A GitHub issue was generated. Open it and click "Submit new issue".',
    });
  };

  return (
    <Layout>
      <div className="mx-auto max-w-2xl">
        <div className="mb-6">
          <h1 className="text-2xl font-extrabold tracking-tight text-ink-900 dark:text-white sm:text-3xl">
            Submit a free resource
          </h1>
          <p className="mt-2 text-ink-600 dark:text-ink-400">
            Fill in the details below — no account or login required on this
            site. When you're ready, we'll generate a pre-filled GitHub issue.
            A GitHub Action validates your submission and auto-merges a pull
            request that updates{' '}
            <code className="rounded bg-ink-100 px-1 py-0.5 text-sm dark:bg-ink-800">resources.json</code>.
            You only need a (free) GitHub account to post the issue.
          </p>
        </div>

        {result && (
          <div className="mb-6 animate-fade-in rounded-lg border border-ink-300 bg-ink-50 p-6 dark:border-ink-700 dark:bg-ink-900">
            <div className="flex items-start gap-3">
              <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-ink-900 text-white dark:bg-white dark:text-ink-950">
                <svg className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                  <path d="M20 6 9 17l-5-5" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </div>
              <div className="min-w-0 flex-1">
                <h2 className="text-lg font-bold text-ink-900 dark:text-white">
                  Your submission is ready!
                </h2>
                <p className="mt-1 text-sm text-ink-600 dark:text-ink-400">
                  Open the GitHub issue below, review the pre-filled details,
                  and click <strong>"Submit new issue"</strong>. Within a
                  minute, a bot will validate your entry and open an
                  auto-merging pull request.
                </p>
                <div className="mt-4 flex flex-wrap gap-2">
                  <a href={result.url} target="_blank" rel="noreferrer" className="btn-primary">
                    <svg className="h-4 w-4" viewBox="0 0 24 24" fill="currentColor">
                      <path d="M12 .5C5.73.5.5 5.73.5 12c0 5.08 3.29 9.39 7.86 10.91.58.11.79-.25.79-.56 0-.28-.01-1.02-.02-2-3.2.7-3.88-1.54-3.88-1.54-.53-1.34-1.3-1.7-1.3-1.7-1.06-.72.08-.71.08-.71 1.17.08 1.79 1.2 1.79 1.2 1.04 1.79 2.73 1.27 3.4.97.11-.76.41-1.27.74-1.56-2.55-.29-5.24-1.28-5.24-5.69 0-1.26.45-2.28 1.19-3.09-.12-.29-.52-1.46.11-3.05 0 0 .97-.31 3.18 1.18a11.02 11.02 0 0 1 5.79 0c2.2-1.49 3.17-1.18 3.17-1.18.63 1.59.23 2.76.11 3.05.74.81 1.19 1.83 1.19 3.09 0 4.42-2.69 5.39-5.25 5.68.42.36.79 1.08.79 2.18 0 1.58-.01 2.85-.01 3.24 0 .31.21.68.8.56A11.51 11.51 0 0 0 23.5 12C23.5 5.73 18.27.5 12 .5z" />
                    </svg>
                    Open GitHub issue →
                  </a>
                  <button onClick={() => setResult(null)} className="btn-ghost">
                    Submit another
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}

        <form onSubmit={submit} className="space-y-6">
          <Field
            label="Category"
            hint="Pick an existing category, or type a new one to create it."
            error={touched.categoryName && errors.categoryName}
          >
            <input
              list="cat-list"
              value={form.categoryName}
              onChange={(e) => set('categoryName', e.target.value)}
              onBlur={() => onBlur('categoryName')}
              placeholder="e.g. Major Cloud Providers"
              className="input"
            />
            <datalist id="cat-list">
              {categories.map((c) => (
                <option key={c.slug} value={c.name} />
              ))}
            </datalist>
            {form.categoryName &&
              !categories.some((c) => c.name.toLowerCase() === form.categoryName.toLowerCase()) && (
                <div className="mt-2 rounded-md bg-ink-100 p-3 text-xs text-ink-600 dark:bg-ink-800 dark:text-ink-300">
                  ✨ New category. Add a short description (optional):
                  <input
                    value={form.newCategoryDescription}
                    onChange={(e) => set('newCategoryDescription', e.target.value)}
                    placeholder="One-line description of this category"
                    className="input mt-2"
                  />
                </div>
              )}
          </Field>

          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
            <Field label="Resource name" error={touched.name && errors.name}>
              <input
                value={form.name}
                onChange={(e) => set('name', e.target.value)}
                onBlur={() => onBlur('name')}
                placeholder="e.g. Google Cloud Platform"
                className="input"
              />
            </Field>
            <Field label="URL" error={touched.url && errors.url}>
              <input
                type="url"
                value={form.url}
                onChange={(e) => set('url', e.target.value)}
                onBlur={() => onBlur('url')}
                placeholder="https://example.com"
                className="input"
              />
            </Field>
          </div>

          <Field
            label="Description"
            hint="What's free about it? Be specific about limits."
            error={touched.description && errors.description}
            counter={`${form.description.length}/400`}
          >
            <textarea
              value={form.description}
              onChange={(e) => set('description', e.target.value)}
              onBlur={() => onBlur('description')}
              rows={3}
              maxLength={400}
              placeholder="e.g. 2 million Cloud Function invocations/month, 5GB storage, 1TB BigQuery queries/month."
              className="input resize-y"
            />
          </Field>

          <Field label="Tier type">
            <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
              {TIERS.map((t) => (
                <button
                  type="button"
                  key={t.value}
                  onClick={() => set('tier', t.value)}
                  className={`rounded-md border p-3 text-left transition ${
                    form.tier === t.value
                      ? 'border-ink-900 bg-ink-900 text-white ring-2 ring-ink-900 dark:border-white dark:bg-white dark:text-ink-950 dark:ring-white'
                      : 'border-ink-200 hover:border-ink-400 dark:border-ink-700 dark:hover:border-ink-500'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-semibold">{t.label}</span>
                    {form.tier === t.value && (
                      <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                        <path d="M20 6 9 17l-5-5" strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                    )}
                  </div>
                  <p className={`mt-1 text-xs ${form.tier === t.value ? 'opacity-80' : 'text-ink-500 dark:text-ink-400'}`}>{t.desc}</p>
                </button>
              ))}
            </div>
            <div className="mt-2">
              <TierBadge tier={form.tier} />
            </div>
          </Field>

          <Field
            label="Tags"
            hint="Comma-separated, 2–20 chars each, letters/numbers/hyphens."
            error={touched.tags && errors.tags}
          >
            <input
              value={form.tags}
              onChange={(e) => set('tags', e.target.value)}
              onBlur={() => onBlur('tags')}
              placeholder="paas, serverless, gcp"
              className="input"
            />
          </Field>

          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
            <Field
              label="Your GitHub handle (optional)"
              error={touched.submittedBy && errors.submittedBy}
              hint="So we can credit you in the PR."
            >
              <input
                value={form.submittedBy}
                onChange={(e) => set('submittedBy', e.target.value)}
                onBlur={() => onBlur('submittedBy')}
                placeholder="octocat"
                className="input"
              />
            </Field>
            <Field label="Note for maintainers (optional)">
              <input
                value={form.note}
                onChange={(e) => set('note', e.target.value)}
                placeholder="Anything we should know?"
                className="input"
              />
            </Field>
          </div>

          <div className="rounded-lg border border-ink-200 bg-ink-50 p-4 dark:border-ink-800 dark:bg-ink-900/50">
            <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-ink-400">
              Live preview
            </p>
            <div className="rounded-md bg-white p-4 ring-1 ring-ink-200 dark:bg-ink-900 dark:ring-ink-800">
              <div className="flex items-center gap-2">
                <span className="font-semibold text-ink-900 underline decoration-ink-300 underline-offset-2 dark:text-white dark:decoration-ink-600">
                  {form.name || 'Resource name'}
                </span>
                <TierBadge tier={form.tier} />
              </div>
              <p className="mt-2 text-sm text-ink-600 dark:text-ink-400">
                {form.description || 'Your description will appear here.'}
              </p>
              {form.tags && (
                <div className="mt-3 flex flex-wrap gap-1.5">
                  {form.tags.split(',').map((t) => t.trim().toLowerCase()).filter(Boolean).slice(0, 6).map((t, i) => (
                    <span key={i} className="tag">{t}</span>
                  ))}
                </div>
              )}
            </div>
          </div>

          <div className="flex items-center gap-3">
            <button type="submit" disabled={submitting} className="btn-primary">
              {submitting ? (
                <><Spinner /> Preparing…</>
              ) : (
                <>
                  <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M12 5v14M5 12h14" strokeLinecap="round" />
                  </svg>
                  Generate GitHub submission
                </>
              )}
            </button>
            <Link to="/" className="btn-ghost">Cancel</Link>
          </div>
          <p className="text-xs text-ink-400">
            By submitting, you agree your contribution may be edited or rejected.
            Duplicates and non-free services will not be accepted. No login is
            required on this site — you only need a GitHub account to post the
            issue that triggers the automated pull request.
          </p>
        </form>
      </div>
    </Layout>
  );
}

function Field({ label, hint, error, counter, children }) {
  return (
    <div>
      <div className="mb-1.5 flex items-baseline justify-between">
        <label className="text-sm font-medium text-ink-700 dark:text-ink-300">{label}</label>
        {counter && <span className="text-xs text-ink-400">{counter}</span>}
      </div>
      {children}
      {error ? (
        <p className="mt-1 text-xs text-red-600 dark:text-red-400">{error}</p>
      ) : hint ? (
        <p className="mt-1 text-xs text-ink-400 dark:text-ink-500">{hint}</p>
      ) : null}
    </div>
  );
}

function Spinner() {
  return (
    <svg className="h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
    </svg>
  );
}
